// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHCIuEl-K66MuDUS-FMKeFFimwgbF63kY',
    appId: '1:820602805085:web:e8ae16244b9058e85ae6b4',
    messagingSenderId: '820602805085',
    projectId: 'aicode-ff349',
    authDomain: 'aicode-ff349.firebaseapp.com',
    storageBucket: 'aicode-ff349.appspot.com',
    measurementId: 'G-BVC9X43BDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOgK3hKQJ_XZb02S7XD_sa2jP8dpxYYM0',
    appId: '1:820602805085:android:32813fc62ad05b8e5ae6b4',
    messagingSenderId: '820602805085',
    projectId: 'aicode-ff349',
    storageBucket: 'aicode-ff349.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2ExtehuWfFL9B8c1MnYQsbGSTjfxj7_Y',
    appId: '1:820602805085:ios:62d5cd98a4e6fe085ae6b4',
    messagingSenderId: '820602805085',
    projectId: 'aicode-ff349',
    storageBucket: 'aicode-ff349.appspot.com',
    iosBundleId: 'com.example.aiCode',
  );
}
